# Generated by Django 4.2.7 on 2023-12-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calidad', '0001_initial'),
        ('personas', '0001_initial'),
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('objetivo', models.TextField()),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('duracion', models.PositiveIntegerField(help_text='Duración en días', verbose_name='Duración')),
                ('lugar', models.CharField(max_length=100)),
                ('fechaIniProgramada', models.DateTimeField(verbose_name='Fecha de Inicio Programada')),
                ('fechaFinProgramada', models.DateTimeField(verbose_name='Fecha de Finalización Programada')),
                ('fechaIniEjecutada', models.DateTimeField(verbose_name='Fecha de Inicio Ejecutada')),
                ('fechaFinEjecutada', models.DateTimeField(verbose_name='Fecha de Finalización Ejecutada')),
                ('presupuestoProgramado', models.PositiveIntegerField(verbose_name='Presupuesto Programado')),
                ('presupuestoEjecutado', models.PositiveIntegerField(verbose_name='Presupuesto Ejecutado')),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial'), ('Virtual', 'Virtual')], max_length=20)),
                ('cupo', models.PositiveIntegerField(default=0)),
                ('asistencia', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('Planeada', 'Planeada'), ('Ejecutada', 'Ejecutada'), ('En Ejecución', 'En Ejecución'), ('Ejecutada Parcialmente', 'Ejecutada Parcialmente'), ('Cancelada', 'Cancelada')], max_length=25)),
                ('observaciones', models.TextField(blank=True, help_text='Novedades presentadas que afectaron la ejecución de la actividad')),
                ('criterios', models.ManyToManyField(to='calidad.criteriodecalidad', verbose_name='Criterios de Calidad')),
                ('dependencias', models.ManyToManyField(to='academia.dependencia')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Planeacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad', models.PositiveSmallIntegerField(choices=[(1, 'Mensual'), (2, 'Bimestral'), (3, 'Trimestral'), (4, 'Cuatrimestral'), (6, 'Semestral'), (12, 'Anual')])),
                ('fechaInicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha de Finalización')),
                ('estado', models.CharField(choices=[('Planeado', 'Planeado'), ('Ejecutado', 'Ejecutado'), ('En Ejecución', 'En Ejecución'), ('Ejecutado Parcialmente', 'Ejecutado Parcialmente'), ('Cancelado', 'Cancelado')], max_length=25)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.programa')),
            ],
            options={
                'verbose_name': 'Planeación',
                'verbose_name_plural': 'Planeaciones',
                'ordering': ['-fechaInicio'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Lista de Asistencia', 'Lista de Asistencia'), ('Acta de Reunión', 'Acta de Reunión'), ('Otras Actas', 'Otras Actas'), ('Oficio Administrativo', 'Oficio Administrativo'), ('Proyecto de Aula', 'Proyecto de Aula'), ('Proyecto de Investigación', 'Proyecto de Investigación'), ('Otro', 'Otro')], max_length=30)),
                ('fechaEv', models.DateTimeField(verbose_name='Fecha')),
                ('fechaReg', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('soporte', models.FileField(upload_to='evidencias/<django.db.models.fields.related.ForeignKey>/')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
                ('docentes', models.ManyToManyField(to='personas.administrativo')),
                ('estudiantes', models.ManyToManyField(to='personas.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='planeacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.planeacion', verbose_name='Planeación'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='programas',
            field=models.ManyToManyField(to='academia.programa'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.administrativo'),
        ),
    ]
