# Generated by Django 4.2.7 on 2023-12-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('director', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.PositiveSmallIntegerField(choices=[(1, '1 Semestre'), (2, '2 Semestres'), (3, '3 Semestres'), (4, '4 Semestres'), (5, '5 Semestres'), (6, '6 Semestres'), (7, '7 Semestres'), (8, '8 Semestres'), (9, '9 Semestres'), (10, '10 Semestres')], default=10, verbose_name='Duración')),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('url', models.URLField(verbose_name='URL')),
                ('director', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['duracion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=14)),
                ('nombre', models.CharField(max_length=100)),
                ('campus', models.CharField(choices=[('cuc', 'Cúcuta'), ('buc', 'Bucaramanga'), ('val', 'Valledupar'), ('bog', 'Bogotá')], default='cuc', max_length=3)),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=14, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name_plural': 'Universidades',
                'ordering': ['nombre', 'campus'],
            },
        ),
    ]
