# Generated by Django 4.2.7 on 2023-12-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocIdentidad', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PA', 'Pasaporte'), ('CD', 'Carnet Diplomático'), ('PP', 'Permiso por Protección Temporal')], default='CC', max_length=2, verbose_name='Tipo de Documento de Identidad')),
                ('numDocIdentidad', models.CharField(max_length=14, verbose_name='Número de Documento de Identidad')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=16, unique=True, verbose_name='Código')),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X')])),
                ('activo', models.BooleanField(default=True)),
                ('graduado', models.BooleanField(default=False)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.programa')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocIdentidad', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PA', 'Pasaporte'), ('CD', 'Carnet Diplomático'), ('PP', 'Permiso por Protección Temporal')], default='CC', max_length=2, verbose_name='Tipo de Documento de Identidad')),
                ('numDocIdentidad', models.CharField(max_length=14, verbose_name='Número de Documento de Identidad')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('codigo', models.CharField(max_length=16, unique=True, verbose_name='Código')),
                ('rol', models.CharField(choices=[('Profesor', 'Profesor'), ('Secretario/a', 'Secretario/a'), ('Director/a de Programa', 'Director/a de Programa'), ('Director/a de Dependencia', 'Director/a de Dependencia')], max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.dependencia')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.programa')),
            ],
            options={
                'ordering': ['apellidos'],
            },
        ),
    ]
